# Configuración de pruebas de humo para Ta-Te-Ti Arbitrator
# @lastModified 2025-10-05
# @version 1.0.0

services:
    # Ta-Te-Ti Arbitrator
    arbitrator:
        build: .
        image: tateti-arbitro:v1.0.0-smoke
        container_name: tateti-arbitrator-smoke
        ports:
            - "4000:4000"
        environment:
            - NODE_ENV=production
            - PORT=4000
            - LOG_LEVEL=info
            - TRUST_PROXY=true
            - RATE_LIMIT_WINDOW_MS=60000
            - RATE_LIMIT_MAX=1000
        networks:
            - tateti-network
        healthcheck:
            test:
                [
                    "CMD",
                    "node",
                    "-e",
                    "import('http').then(h=>h.get('http://localhost:4000/api/stream/status', r=>process.exit(r.statusCode===200?0:1)))",
                ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

    # Player 1 - Random Bot
    player1:
        build:
            context: ./players/random-bot
            tags: [tateti-random-bot:v1.0.0-smoke]
        container_name: tateti-random-bot-1-smoke
        ports:
            - "3001:3001"
        environment:
            - PORT=3001
            - PLAYER_NAME=RandomBot1
        networks:
            - tateti-network
        depends_on:
            arbitrator:
                condition: service_healthy

    # Player 2 - Random Bot
    player2:
        build:
            context: ./players/random-bot
            tags: [tateti-random-bot:v1.0.0-smoke]
        container_name: tateti-random-bot-2-smoke
        ports:
            - "3002:3002"
        environment:
            - PORT=3002
            - PLAYER_NAME=RandomBot2
        networks:
            - tateti-network
        depends_on:
            arbitrator:
                condition: service_healthy

networks:
    tateti-network:
        driver: bridge
